server {
    listen 80;
    listen 443 ssl;
    server_name plazamoyobamba.online;
    
    ssl_certificate /etc/letsencrypt/live/plazamoyobamba.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/plazamoyobamba.online/privkey.pem;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
    }

    location ~ /\.ht {
        deny all;
    }
}
